### ISSUE TITLE
QA_Defect_Manual speech signal-to-symbol transformatio_04

### ISSUE THREAD

**Issue by kolliSuman** [Virtual-Labs/speech-signal-processing-iiith#3] opened 2015-09-29 10:16 UTC
Defect Description:
In the experiment page of the "Manual speech signal-to-symbol transformation", without clicking on the play button the record button is enabled where the record button should be disabeled.
.

Actual Result :
In the experiment page of the "Manual speech signal-to-symbol transformation", without clicking on the play button the record button is enabled

Environment :
OS: Windows 7, Linux
Browsers: Firefox,Chrome
Bandwidth : 100mbps
Hardware Configuration:8GBRAM ,
Processor:i5

Severity : S2

**Comment by BSravanthi** [comment] 2016-06-10 07:30
Closing the issue as the issue is differed.

**Closed by BSravanthi** 2016-06-10 07:30 UTC
Labels: Category :Functionality, Developed by: VLEAD, Status : Differed
