### ISSUE TITLE
QA_Basics of DSP_1.0_Experiment_p1

### ISSUE THREAD

**Issue by kolliSuman** [Virtual-Labs/speech-signal-processing-iiith#11] opened 2016-04-21 09:51 UTC
Defect Description:
In the experiment page of the "Basics of DSP", without clicking on the play button the record button is enabled where the record button should be disabled.

Actual Result :
In the experiment page of the "Basics of DSP", without clicking on the play button the record button is enabled

Environment:
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

 Test Step Link:
https://github.com/Virtual-Labs/peech-signal-processing-iiith/blob/master/test-cases/integration_test-cases/Basics%20of%20DSP_1.0/Basics%20of%20DSP_1.0_07_Experiment_p1.org

Attachment:
![basics](https://cloud.githubusercontent.com/assets/14869397/14705391/deef20d2-07d6-11e6-8b5e-b0b0951497bf.png)

**Comment by BSravanthi** [comment] 2016-06-10 07:25
Closing the issue as the issue is differed.

**Closed by BSravanthi** 2016-06-10 07:25 UTC
Labels: Category: Functionality, Developed by: VLEAD, Release Number: 1, Severity: S2, Status : Differed
